export const Title = {
  alignSelf: 'flex-start',
  fontFamily: 'Roboto',
  fontSize: '18px',
  letterSpacing: 0,
  color: '#78909C',
  opacity: 1,
};

export const classes = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  tituloDesafio: {
    width: 308,
    height: 50,
    background: '0% 0% no-repeat padding-box',
    border: '#78909C',
    opacity: 1,
  },
  contadorCaracteres: {
    paddingTop: '5px',
    paddingRight: '20px',
    alignSelf: 'center',
    fontFamily: 'Roboto',
    fontSize: '12px',
    letterSpacing: 0,
    color: '#78909C',
    opacity: 1,
  },
  contadorCaracteresEditor: {
    width: '100%',
    fontFamily: 'Roboto',
    fontSize: '12px',
    letterSpacing: 0,
    color: '#78909C',
    opacity: 1,
    paddingRight: 5,
    border: '0.5px solid #CCCCCC',
    borderTop: 'none',
    textAlign: 'end',
    // borderLeft: 'none',
    // borderRight: 'none',
  },
  containerEditor: {
    marginTop: 10,
    width: '100%',
  },
  containerEditorCabecalho: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingBottom: '15px',
  },
  containerEditorCabecalhoNumPag: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    letterSpacing: 0,
    color: '#78909C',
    opacity: 1,
  },
  containerEditorCabecalhoAddHTML: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    letterSpacing: 0,
    color: '#3796F6',
    opacity: 1,
  },
  containerEditorCabecalhoX: {
    color: '#78909C',
  },
  containerDivButtoms: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    flexGrow: 1,
    justifyContent: 'center',
    marginTop: 20,
  },
  btnAddPagina_VizualizarPrevia: {
    backgroundColor: '#FFFFFF',
    color: '#3796F6',
    boxShadow: 'none',
  },
};
