export const classes = {
  divDialogContentExt: {
    backgroundColor: '#9EADBA',
    borderRadius: 35,
    margin: '30px 60px 30px 60px',
  },
  divDialogContentSpeecker: {
    backgroundColor: '#FFF',
    width: 150,
    height: 12,
    borderRadius: '100px',
    marginTop: '2%',
    position: 'absolute',
    marginLeft: '24%',
  },
  divDialogContentSensor: {
    backgroundColor: '#FFF',
    width: 12,
    height: 12,
    borderRadius: '50%',
    marginLeft: '15%',
    position: 'absolute',
    marginTop: '4%',
  },
  divDialogContentText: {
    backgroundColor: '#F5F4F5',
    minHeight: 760,
    maxHeight: '100%',
    minWidth: 350,
    maxWidth: 'auto',
    borderRadius: 25,
    marginTop: 50,
    marginBottom: 40,
  },
  divDialogTitleContent: { display: 'flex', justifyContent: 'space-around' },
  divDialogTitle: {
    fontFamily: 'Roboto',
    fontSize: 16,
    fontWeight: 'bold',
    color: '#78909C',
  },
  divDialogTitleConteudo: {
    padding: '0px 0px 0px 20px',
    backgroundColor: '#D2D9DD',
  },
  divDialogTitleContentAndPage: {
    fontFamily: 'Roboto',
    fontSize: 16,
    color: '#78909C',
    display: 'flex',
    justifyContent: 'space-between',
    marginRight: 20,
  },
  divDialogContentInnerHTML: {
    padding: 20,
    textAlign: 'justify',
    display: 'flex',
    flexDirection: 'column',
  },
  divDialogContentMicrophone: {
    backgroundColor: '#FFF',
    width: 150,
    height: 12,
    borderRadius: '100px',
    marginTop: -20,
    position: 'absolute',
    marginLeft: '24%',
  },
  divNavigation: {
    backgroundColor: '#fff',
    display: 'flex',
    height: 60,
    marginTop: 5,
    marginBottom: 5,
    borderRadius: 5,
    border: '1px solid #D2D9DD',
  },
  divNavigationIndex: {
    backgroundColor: '#D2D9DD',
    width: 50,
    height: 50,
    color: '#fff',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontSize: 18,
    borderRadius: 5,
    margin: 5,
  },
  divNavigationTitle: {
    fontFamily: 'Roboto',
    fontSize: 14,
    color: '#78909C',
    display: 'flex',
    alignItems: 'center',
  },
};
