export const Title = {
  alignSelf: 'flex-start',
  fontFamily: 'Roboto',
  fontSize: '18px',
  letterSpacing: 0,
  color: '#78909C',
  opacity: 1,
};

export const classes = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  tituloDesafio: {
    width: '20%',
    padding: '10px 10px',
    marginBottom: 5,
    background: '0% 0% no-repeat padding-box',
    border: 'solid 1px #78909C',
    borderRadius: 5,
    opacity: 1,
  },
  contadorCaracteres: {
    width: '20%',
    fontFamily: 'Roboto',
    fontSize: '12px',
    letterSpacing: 0,
    color: '#78909C',
    opacity: 1,
  },
  contadorCaracteresEditor: {
    width: '100%',
    fontFamily: 'Roboto',
    fontSize: '12px',
    letterSpacing: 0,
    color: '#78909C',
    opacity: 1,
    paddingRight: 5,
  },
  containerEditor: {
    marginTop: 10,
  },
  containerEditorCabecalho: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingBottom: '15px',
  },
  containerEditorCabecalhoNumPag: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    letterSpacing: 0,
    color: '#78909C',
    opacity: 1,
  },
  containerEditorCabecalhoAddHTML: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    letterSpacing: 0,
    color: '#3796F6',
    opacity: 1,
  },
  containerEditorCabecalhoX: {
    color: '#78909C',
  },
  containerDivButtoms: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    flexGrow: 1,
    justifyContent: 'center',
    marginTop: 20,
  },
  btnAddPagina_VizualizarPrevia: {
    backgroundColor: '#FFFFFF',
    color: '#3796F6',
    boxShadow: 'none',
  },
  divDialogContentExt: {
    backgroundColor: '#9EADBA',
    borderRadius: 35,
    margin: '30px 60px 30px 60px',
  },
  divDialogContentSpeecker: {
    backgroundColor: '#FFF',
    width: 150,
    height: 12,
    borderRadius: '100px',
    marginTop: '2%',
    position: 'absolute',
    marginLeft: '24%',
  },
  divDialogContentSensor: {
    backgroundColor: '#FFF',
    width: 12,
    height: 12,
    borderRadius: '50%',
    marginLeft: '15%',
    position: 'absolute',
    marginTop: '4%',
  },
  divDialogContentText: {
    backgroundColor: '#F5F4F5',
    minHeight: 760,
    maxHeight: '100%',
    minWidth: 401,
    maxWidth: 'auto',
    borderRadius: 25,
    marginTop: 50,
    marginBottom: 40,
  },
  divDialogTitleContent: { display: 'flex', justifyContent: 'space-around' },
  divDialogTitle: {
    fontFamily: 'Roboto',
    fontSize: 16,
    fontWeight: 'bold',
    color: '#78909C',
  },
  divDialogTitleConteudo: {
    padding: '0px 0px 0px 20px',
    backgroundColor: '#D2D9DD',
  },
  divDialogTitleContentAndPage: {
    fontFamily: 'Roboto',
    fontSize: 16,
    color: '#78909C',
    display: 'flex',
    justifyContent: 'space-between',
    marginRight: 20,
  },
  divDialogContentInnerHTML: {
    padding: 20,
    textAlign: 'justify',
  },
  divDialogContentMicrophone: {
    backgroundColor: '#FFF',
    width: 150,
    height: 12,
    borderRadius: '100px',
    marginTop: -20,
    position: 'absolute',
    marginLeft: '24%',
  },
};
